#!/usr/bin/env bash
# to split a multi-fasta file into individual fasta files (eg an assembly into 1 file per contig)
# usage: bash splitfasta assembly.fasta

c=1
for part in $(cat $1 | bioawk -c fastx '{print ">"$name"##"$seq}')
do
	echo $part | sed 's/##/\n/' > contig$c.fasta
	c=$(($c + 1))
done
